"""empty message

Revision ID: 0652257b63f7
Revises: ad2f09e5b4fb
Create Date: 2024-12-08 18:36:23.179607

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0652257b63f7'
down_revision = 'ad2f09e5b4fb'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('private_event_ends', sa.DateTime(), nullable=True))
        batch_op.add_column(sa.Column('last_activated', sa.DateTime(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_column('last_activated')
        batch_op.drop_column('private_event_ends')

    # ### end Alembic commands ###
