"""empty message

Revision ID: 1de254e10d3f
Revises: fd0b6922e5e9
Create Date: 2024-12-17 16:52:59.932683

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1de254e10d3f'
down_revision = 'fd0b6922e5e9'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('username', sa.String(length=50), nullable=False))
        batch_op.add_column(sa.Column('strava_refresh_token', sa.String(length=255), nullable=True))
        batch_op.add_column(sa.Column('strava_expires_at', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('private_event_ends', sa.DateTime(), nullable=True))
        batch_op.add_column(sa.Column('last_activated', sa.DateTime(), nullable=True))
        batch_op.add_column(sa.Column('linked_accounts', sa.Boolean(), nullable=True))
        batch_op.add_column(sa.Column('overall_points', sa.Integer(), nullable=True))
        batch_op.create_unique_constraint(None, ['username'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='unique')
        batch_op.drop_column('overall_points')
        batch_op.drop_column('linked_accounts')
        batch_op.drop_column('last_activated')
        batch_op.drop_column('private_event_ends')
        batch_op.drop_column('strava_expires_at')
        batch_op.drop_column('strava_refresh_token')
        batch_op.drop_column('username')

    # ### end Alembic commands ###
