"""empty message

Revision ID: 2d5f0d051b4a
Revises: 0f52a6b45f68
Create Date: 2024-12-02 07:22:54.983949

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '2d5f0d051b4a'
down_revision = '0f52a6b45f68'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('monthly_data', sa.JSON(), nullable=True))
        batch_op.add_column(sa.Column('yearly_data', sa.JSON(), nullable=True))
        batch_op.add_column(sa.Column('monthly_last_updated', sa.DateTime(), nullable=True))
        batch_op.add_column(sa.Column('yearly_last_updated', sa.DateTime(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_column('yearly_last_updated')
        batch_op.drop_column('monthly_last_updated')
        batch_op.drop_column('yearly_data')
        batch_op.drop_column('monthly_data')

    # ### end Alembic commands ###
