"""empty message

Revision ID: 58d626bd5394
Revises: 1de254e10d3f
Create Date: 2024-12-21 17:53:08.110744

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import sqlite

# revision identifiers, used by Alembic.
revision = '58d626bd5394'
down_revision = '1de254e10d3f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.alter_column('username',
               existing_type=sa.VARCHAR(length=50),
               nullable=False)
        batch_op.alter_column('strava_id',
               existing_type=sa.VARCHAR(length=50),
               nullable=False)
        batch_op.alter_column('strava_access_token',
               existing_type=sa.VARCHAR(length=255),
               nullable=False)
        batch_op.alter_column('strava_refresh_token',
               existing_type=sa.VARCHAR(length=255),
               nullable=False)
        batch_op.alter_column('strava_expires_at',
               existing_type=sa.INTEGER(),
               nullable=False)
        batch_op.create_unique_constraint('username_col', ['username'])
        batch_op.create_unique_constraint('strava_id_col', ['strava_id'])
        
        batch_op.drop_column('monthly_last_updated')
        batch_op.drop_column('password_hash')
        batch_op.drop_column('yearly_last_updated')
        batch_op.drop_column('last_bucks_update')
        batch_op.drop_column('last_activated')
        batch_op.drop_column('linked_accounts')
        batch_op.drop_column('private_event_ends')
        batch_op.drop_column('yearly_data')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('yearly_data', sqlite.JSON(), nullable=True))
        batch_op.add_column(sa.Column('private_event_ends', sa.DATETIME(), nullable=True))
        batch_op.add_column(sa.Column('linked_accounts', sa.BOOLEAN(), nullable=True))
        batch_op.add_column(sa.Column('last_activated', sa.DATETIME(), nullable=True))
        batch_op.add_column(sa.Column('last_bucks_update', sa.DATETIME(), nullable=True))
        batch_op.add_column(sa.Column('yearly_last_updated', sa.DATETIME(), nullable=True))
        batch_op.add_column(sa.Column('password_hash', sa.VARCHAR(length=128), nullable=False))
        batch_op.add_column(sa.Column('monthly_last_updated', sa.DATETIME(), nullable=True))
        batch_op.drop_constraint(None, type_='unique')
        batch_op.drop_constraint(None, type_='unique')
        batch_op.alter_column('strava_expires_at',
               existing_type=sa.INTEGER(),
               nullable=True)
        batch_op.alter_column('strava_refresh_token',
               existing_type=sa.VARCHAR(length=255),
               nullable=True)
        batch_op.alter_column('strava_access_token',
               existing_type=sa.VARCHAR(length=255),
               nullable=True)
        batch_op.alter_column('strava_id',
               existing_type=sa.VARCHAR(length=50),
               nullable=True)
        batch_op.alter_column('username',
               existing_type=sa.VARCHAR(length=50),
               nullable=True)

    # ### end Alembic commands ###
